version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.6
  install:
  - method: pip3
    path: .
    extra_requirements:
    - docs
submodules:
  include:
     - "docs/user_guide/notebooks"
  recursive: true
