version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
python:
  version: 3.6
  install:
    - method: setuptools
      path: .
      requirements: docs/requirements.txt
    - method: pip
      path: .
    - requirements: docs/requirements.txt
submodules:
  include:
     - "docs/user_guide/notebooks"
  recursive: true
