{% set name = "cassiopeia" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/YosefLab/Cassiopeia.git

build:
  number: 0
  script: "{{ PYTHON }} setup.py build; {{ PYTHON }} setup.py build_ext --inplace; {{ PYTHON }} setup.py bdist_wheel; {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - setuptools
    - pip
    - Cython
  run:
    - python

test:
  imports:
    - cassiopeia
    - cassiopeia.ProcessingPipeline
    - cassiopeia.TreeSolver
#   imports:
#     - numpy
#     - cassiopeia

about:
  home: https://github.com/YosefLab/Cassiopeia
  license: MIT
  license_family: MIT
  summary: A Package for Cas9-Enabled Single Cell Lineage Tracing Tree Reconstruction
