## Example config file for TargetSeqAnalysis pipeline
---
sample_file:
    - BL_output/BL.moleculetable.filtered.txt
output_file:
    - BL.alleleTable.txt
output_dir:
    - BL_lg_output
min_cluster_size:
    - 1
min_allele_thresh:
    - 0.1
verbose:
    - False
